### ISSUE TITLE
Use hertz-swagger to enhance api documents

### ISSUE THREAD

**Issue by TremblingV5** [TremblingV5/DouTok#103]
## What

Use hertz-swagger to enhance api documents

## Details

To facilitate front-end development, we may need an api documents. As we know,  swagger is a good way to do this job. We can read the documents for `hertz-swagger`.

https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/swagger/

We need to add some comments to tell us what the api need and what to response. Also, we may add some commands by using `Makefile` to let us to use `make ....` to generate the documents of api.

**Comment by AbigailJixiangyuyu** [comment]
please assign me
