### ISSUE TITLE
读取配置的方式被修改

### ISSUE THREAD

**Issue by AbigailJixiangyuyu** [TremblingV5/DouTok#132]
## Question
![image](https://github.com/TremblingV5/DouTok/assets/129409676/61bc7e06-9b82-4a9c-8d8e-d80ba50f3867)
为什么在这次提交的时候很多修改被删除了
![image](https://github.com/TremblingV5/DouTok/assets/129409676/2e294019-08c6-40f1-924f-df545fd3f29f)
我认为被删除的方式是更好的方法

**Comment by TremblingV5** [comment]
这里其实没有被删除，我把这一块重构到了`configurator`里面去，用统一的`configurator.Load`方法去加载配置，所有的配置操作都在`Load`方法里面去做。

在开发其他模块或功能需要加载配置的情况下，只需要调用统一的`configurator.Load`即可保证使用同一套方式去加载配置，不需要单独考虑优先级。如果读文件和读环境变量的方法全部单独，在写其他功能的时候可能因为不同人的不同习惯或者是偶然的因素，导致读取变量的优先级改变等。

**Comment by AbigailJixiangyuyu** [comment]
# 我有一些建议和问题
## 问题
![image](https://github.com/TremblingV5/DouTok/assets/129409676/9dd0080c-c66e-4791-8370-ae02d77c7e39)
这个上下文参数是否可以去掉，这里没有涉及到协程

我注意到使用的Tag是
![image](https://github.com/TremblingV5/DouTok/assets/129409676/201a9e47-f476-4873-80a0-97d661b78a01)
这种全路径形式
而非通过结构体名称递归传递下来，会导致代码冗杂
而且配置结构体的形式，和YAML的结构可能存在不一致性

### 关于配置优先级
![image](https://github.com/TremblingV5/DouTok/assets/129409676/f0f9858f-649d-4c22-978e-01907f3b867a)
我认为规定不同配置的优先级是有必要的，这对一个团队协作的一致性很重要，而非代码去适应不同开发者的习惯。并且 `configurator.Load` 实际上也存在优先级，即为 file > env 。
对不同配置优先级的规定，viper的文档里已经有了建议。

## 建议
![image](https://github.com/TremblingV5/DouTok/assets/129409676/8ebbb8f8-63f3-4072-a560-75e27c2c7481)
这里
![image](https://github.com/TremblingV5/DouTok/assets/129409676/c5d85044-d4a0-489f-abf2-26ae189953cf)
用这种方式是否更好

**Comment by TremblingV5** [comment]
## Load函数的context

可以删掉，本意是想看有没有什么需要的东西可以塞进去，但目前来看也还没有，日志可以留在外层去做，所以删掉也无所谓。

## 配置类的Tag

确实是会造成代码冗余。

但是感觉可以保留这个tag，在这个tag为空时，去读取递归传递的变量属性作为`configPath`。保留这个Tag的原因在于，代码中将不同组件的配置划分给不同的配置结构体有利于增强代码可读性，在有`configPath`的情况下可以自定义一些配置项的具体读取路径，可以提升一些灵活性。

## 配置体结构与Yaml结构不同

`configPath`这个tag在一定程度上可以缓解这个问题，但是配置结构体和Yaml结构不同这个问题是难以避免的，对于任何一个软件，配置文件肯定是得按照一定的格式结构去进行编写的。

## 配置优先级问题

### 是否应该有配置优先级

是，在启动软件时应该有明确的配置优先级，否则可能造成配置项混淆，导致启动方式配置意义不明

`不需单独考虑配置优先级`指的是开发某个需要加载配置的contributor不需要单独考虑应该先加载文件还是先加载环境变量，到底哪个优先级更高全部交给统一的`Load`函数去控制。不同配置之间的优先级更多的像是一种“约定”，而具体哪个更优先通常来说不是什么“大问题”。

### 使用什么库去进行配置

我对viper的了解确实不是那么多。

像上面所说，配置优先级更多是一种约定，具体哪个更优先不是什么“大问题”。哪个更优先对于我来说确实比较无所谓。

之前没有使用viper去读环境变量，因为看到viper读环境变量需要单独调用一个类似`Bind()`的方法进行绑定，当时觉得这部分代码写出来又是一堆，不如现在这样用结构体写的方式更优雅。当然也有可能是我当时看漏了，如果viper也有类似的在结构体后面打tag来生命环境变量的key和环境变量key的前缀的话，全部替换成viper也可以。

## switch-case这部分代码

我觉得用哪个都还好，改成下面那样也是可以的。viper自己应该也是在获取不同类型配置的各个函数里面再去调用类型转换函数的

**Comment by AbigailJixiangyuyu** [comment]
那可以把Run on windows 那部分合并了吗，我这没法往下开发

**Comment by TremblingV5** [comment]
> 那可以把Run on windows 那部分合并了吗，我这没法往下开发

@AbigailJixiangyuyu 

已经合掉了。
