### ISSUE TITLE
关于int64精度丢失的问题

### ISSUE THREAD

**Issue by AbigailJixiangyuyu** [TremblingV5/DouTok#135]
我注意到一些接口返回了int64类型的数据，如user_id。
但由于前端js是使用双精度浮点型接收该类数据，会导致数据失真，需要进行处理，将int64转换为string类型再返回。我有一些方案，但不知道哪种方案更好。
1. 使用中间件拦截返回数据进行重写
2. 在`handler.SendResponse` 内部处理结构体
3. 修改hertz的Marshal函数

**Comment by AbigailJixiangyuyu** [comment]
hertz底层默认使用的`jsonMarshalFunc`函数是将`int64`解析为`float64`处理的

**Comment by AbigailJixiangyuyu** [comment]
或者就是手动处理包含`int64`的返回的结构体，修改为`string`类型

**Comment by TremblingV5** [comment]
可以通过打tag的方式，让结构体在返回数据的时候自动将其转换为string

**Comment by TremblingV5** [comment]
在对应结构体的tag里加上` json:"id,string"`应该就可以了（至少gin这个样子是可以的）

**Comment by AbigailJixiangyuyu** [comment]
great
