### ISSUE TITLE
How to start the first unit Testing

### ISSUE THREAD

**Issue by 2084348916** [TremblingV5/DouTok#140]
## Question
个人想参与到DouTok的开发中。在看过“DouTok从0到1小帮手”后，想从编写单元测试开始。但我不知道怎么开始，请问能提供些学习材料和建议吗？（基本没有项目相关经验）

**Comment by BaiZe1998** [comment]
感谢你关注到DouTok，从单元测试开始，是学习一个开源项目最好的打开方式。

单元测试通常包括编写测试代码，以确保被测试的代码在各种情况下都能正常工作。Go语言的测试通常使用标准库中的testing包进行编写。

以下是一个简单的示例，演示如何编写一个用于测试的Go语言文件和测试文件。假设我们有一个简单的函数，它计算两个整数的和：
```golang
// main.go

package main

func Add(a, b int) int {
	return a + b
}
```
现在，我们将编写一个单元测试文件来测试Add函数：
```golang
// main_test.go

package main

import "testing"

func TestAdd(t *testing.T) {
	cases := []struct {
		a, b, expected int
	}{
		{1, 2, 3},
		{0, 0, 0},
		{-1, 1, 0},
		{10, -5, 5},
	}

	for _, tc := range cases {
		actual := Add(tc.a, tc.b)
		if actual != tc.expected {
			t.Errorf("Add(%d, %d): expected %d, got %d", tc.a, tc.b, tc.expected, actual)
		}
	}
}
```
你的工作是，将单元测试的粒度尽可能细，且编写的测试代码只针对与被测试对象的功能，给出输入和预期希望得到的输出，对于被测试对象内部依赖的db、外部服务等可以通过 mock 的方式，进行替换，因为它已经超过了“单元”的维度，是集成测试的一部分。

关于 mock 类，可以自定义，也可以借助工具生成，比如可以了解相关工具：
https://github.com/uber-go/mock

**Comment by TremblingV5** [comment]
单元测试也可以概括为：针对某个函数，给定输入，它应该给出某个意料之内的输出。对于一个函数，除了可以在使用场景下进行测试外，首先应该保证其逻辑是符合预期的。

单元测试的一个重要指标是覆盖率，每个if条件之后的代码块都应该被尽可能的覆盖到。

我刚刚在DouTok中找了2处可以添加单元测试的地方：

- `./pkg/utils/session_id.go`
- `./pkg/cache/map.go`

如果你愿意，你可以考虑从这2个文件入手，遵循如下步骤去完成单元测试：

1. 阅读对应文件中的代码，理解要编写单元测试的函数的基本功能
2. 在同目录下创建`xxx_test.go`，并准备在其中编写单元测试
3. 命名一个`TestXXX`的函数，用于执行单元测试用例
4. 确定函数的入参，并执行函数
5. 通过相关的断言函数，如`require`包、`testing.T`进行断言，判断执行函数的结果是否正确
6. 再次审视函数内部代码，判断单元测试是否已经尽可能覆盖所有条件分支代码并进行完善

可以先在自己的分支上进行修改，然后提交PR，如果有问题可以根据PR再进行交流

**Comment by 2084348916** [comment]
抱歉，没注意到要关issue
