### ISSUE TITLE
Open source protocol issue

### ISSUE THREAD

**Issue by L2ncE** [TremblingV5/DouTok#90]
Hello~
我注意到这个 repo 的 REAMDE & 图片与 [FreeCar](https://github.com/CyanAsterisk/FreeCar) 风格类似。如果有借鉴 [FreeCar](https://github.com/CyanAsterisk/FreeCar) 的话，请遵循 [GPL-3.0 license](https://github.com/CyanAsterisk/FreeCar/blob/main/LICENSE)。

**Comment by TremblingV5** [comment]
好的，不过我们应该没有借鉴，所有图片均为成员使用不同工具绘制
